"""Batch 11 pools for X + Bluesky (Axel "Blitz" Beaumont character sheet).

Same rules as blitz_pools.py: dash free, no invented figures, no advice, no
returns language, no banned phrases, verified with humanize_rules before use.
Every line is 10 to 18 words so two lines plus a tag line still fit inside the
X 280 character limit.

Voice: fast hands, scalps, gaps, premarket alarms, gamer energy, zero ego
about being early, plus the newer sheet note that the reading comes first.
"""

OPENERS_11 = [
    "I do not chase. I wait at the level and let it come to me.",
    "My whole edge is being gone before the thesis gets long.",
    "The first 40 minutes decide my day. The rest is paperwork.",
    "I trade what is moving, not what is trending on my feed.",
    "Premarket is my study hall. The open is the exam.",
    "Small size until the setup proves itself. Then I press.",
    "I lost money being right too early. Now I wait for the tape.",
    "The chart is the boss and I read the brief before the bell.",
    "Every trade gets an exit before it gets a reason.",
    "I would rather be bored at the open than stuck at the close.",
    "Gap ups get respect. Gap fills get a plan. Both get a stop.",
    "I keep my losses smaller than my patience. That is the whole trick.",
    "The alert does the watching so I can do the thinking.",
    "Fast hands, boring rules. The boring part pays the bills.",
    "I do not need to be early. I need to be paid.",
    "Scalping taught me more about myself than any book did.",
    "I trade the reaction, never the prediction.",
    "Green days test my ego. Red days test my process.",
    "My stops are not pessimistic. They are what keeps me in the game.",
    "The crowd buys the headline. I wait for the second candle.",
    "Volume is the receipt. No volume, no conviction.",
    "I stopped arguing with the tape and started listening faster.",
    "If a chart needs a story to work, I am out.",
    "Nobody pays me for opinions. They pay me for exits.",
    "I plan the trade in the quiet and execute it in the noise.",
    "My best trades feel obvious in hindsight and boring at the time.",
    "Risk first, reward second, ego never.",
    "I let the first move happen without me. There is always a second.",
    "Discipline is the part of the strategy nobody screenshots.",
    "One clean setup beats ten clever ideas before the bell.",
    "I read the filing for homework and the tape for timing.",
    "The open is chaos with a schedule. I like schedules.",
    "I am not faster than machines. I am just more honest about my risk.",
    "My watchlist is short because my attention is expensive.",
    "I stopped revenge trading the day I started writing trades down.",
    "Levels are opinions that keep happening. I respect them.",
    "Nothing ruins a good plan like a smartphone at the open.",
    "I scalp the noise and hold the understanding.",
    "The trade I skip teaches me as much as the one I take.",
    "If I cannot explain the exit, I do not deserve the entry.",
    "I trade one market, one setup, one hour. Boring by design.",
    "Fast money respects slow research. That mix is the whole ape.",
    "My stop loss is the only part of the plan that never argues.",
    "The premarket tells you the mood. The options chain tells you the size.",
    "I like a market that scares the crowd before breakfast.",
    "Being flat is a position and sometimes it is the winning one.",
    "I do not predict the gap. I show up prepared for either direction.",
    "Heat means nothing without size control. Ask any blown account.",
    "My edge is a routine I repeat when I do not feel like it.",
    "Nobody ever destroyed an account taking a small loss quickly.",
    "I read three lines of a filing and one chart before I click anything.",
    "The tape has a mood. The levels have a memory.",
    "Faster entries, slower exits, zero storytelling.",
    "I am allowed to be wrong. I am not allowed to be stubborn.",
    "Every session is a scrimmage. The recap is where I level up.",
    "I click less than I used to and I sleep more than I did.",
    "Setup, size, stop, exit. Say it in that order every time.",
    "The chart does not care about my opinion and that is the appeal.",
    "I keep a notebook of mistakes. It is the cheapest tuition available.",
    "Even the fast money reads. Especially the fast money reads.",
    "I would rather miss a move than inherit a position I do not understand.",
    "Green candles are loud. Good exits are quiet.",
    "The best trade of my week was usually the one I almost skipped.",
    "My plan is written before the bell and followed after it.",
    "Premarket volume picks my candidates. The open picks my size.",
    "I do not trade feelings, and I do not trade to feel something.",
    "The first hour is a test of preparation, not of prediction.",
    "I stopped needing to be right and started needing to be repeatable.",
    "Small wins stacked fast still beat one dramatic swing.",
    "Ape reads slow, clicks fast, sleeps fine.",
]

BODIES_11 = [
    "Level breaks, alert fires, plan executes. No debating in the middle.",
    "One setup drilled until it is boring. Boring is repeatable.",
    "Gap and go, gap and fade. I have a page for each before the bell.",
    "The stop is set at entry, so the decision is already made.",
    "I take the trade the plan described, not the one I feel like taking.",
    "If the volume is not there, the level does not count.",
    "I size down when my pulse goes up. It has saved me more than once.",
    "The recap matters more than the entry. That is where the habit forms.",
    "Preparation is free. Panic at the open is not.",
    "I write the exit price down before I write the entry.",
    "The crowd waits for confirmation and pays for it at the highs.",
    "Nothing in the tape is personal, which is why I can watch it all day.",
    "Risk is a number I choose, not a feeling I discover later.",
    "I trade the plan on the days it feels wrong. That is the job.",
    "Reading the filing first means the headline cannot surprise me as much.",
    "A small loss taken fast is cheaper than a big loss discussed slowly.",
    "Heat is fine. Heat without a stop is how accounts end.",
    "My best days start with nothing on the screen and a written plan.",
    "The alert fired at the level, not at my mood. That is the point.",
    "I keep cash back for the second chance the market usually offers.",
    "The setup repeats. My attention is the variable that changes.",
    "Slower reading, faster clicking. Both halves matter.",
    "I do not add to a loser. I refund a mistake.",
    "The first candle lies more often than the second one.",
    "I stopped trying to catch the whole move and started catching mine.",
    "Every level is a claim about where sellers showed up before.",
    "The market pays for preparation and charges for improvisation.",
    "I keep the same size in the red and the green. Ego is not a variable.",
    "One honest review of my own tape beats a week of other people's calls.",
    "The exit is a decision made in the quiet, not in the squeeze.",
    "If I cannot see the risk, I do not take the trade. Simple filter.",
    "The tape rewards speed and punishes speed without a stop.",
    "I check the sector before I check the chart. Context first.",
    "Boring rules make exciting months possible.",
    "I trade the same two or three patterns until they are muscle memory.",
    "Nothing gets my size until it gets my attention twice.",
    "The premarket gap told the story before the bell did.",
    "I log the reason for every click. Later me reads it and cringes.",
    "Rest is a risk tool. Tired hands click wrong.",
    "The chart is a record, not a prophecy, and I trade records.",
    "I would rather take three clean setups than chase a dozen.",
    "The mood of the tape is a data point, not a decision.",
    "My best exits were planned when the trade looked easy.",
    "Screen time is not research time. They feel the same at midnight.",
    "Cash is a position and patience is the strategy it buys.",
    "I let the plan decide and the market grade it.",
    "No thesis survives a position that is too big for the account.",
    "Losses are part of the rent. Not paying rent is not an option.",
    "I keep the rules short enough to remember under pressure.",
    "The paper trade taught me more than the third opinion did.",
    "Volume confirms the level or the level is just a guess.",
    "I stopped trading the news and started trading the reaction to it.",
    "Second chances come at better prices for the patient.",
    "The stop is not a suggestion and my mood does not get a vote.",
    "I read the release, then I check the tape, then I decide.",
    "The best edge I own is leaving the screen when the plan is done.",
    "Crowded trades have crowded exits. I plan mine early.",
    "A clear process turns a scary open into an ordinary one.",
    "Consistency is a boring compound that looks like nothing for weeks.",
    "I keep a note of what the tape told me and whether I listened.",
    "The market opens a door every day. I wait for one I recognize.",
    "My size reflects conviction, not adrenaline.",
    "Filing first, chart second, click last. Same order, every session.",
    "I do not trade to feel clever. I trade to stay boring and paid.",
    "Nothing teaches sizing like one position that was too large.",
    "The routine is the edge. The rest is just clicks.",
    "Flat is fine. Forced is not.",
    "I review the loss before I review the win. Always.",
    "Fast money and slow reading are not opposites. They are a pair.",
    "The alert is the employee. I am the management.",
    "Every screenshot of a win hides ten unposted stops.",
]

CLOSERS_11 = [
    "Plan first. Click fast. Leave on time.",
    "Read slow. Click fast. Sleep fine.",
    "Level, size, stop. In that order.",
    "One setup. One hour. Zero ego.",
    "Small loss now beats big lesson later.",
    "The exit is the strategy.",
    "Prepare in the quiet. Perform in the noise.",
    "Boring rules, fast hands.",
    "Flat is a position too.",
    "Risk first, reward second.",
    "Less clicking, more planning.",
    "The plan clicks. Not the mood.",
    "Speed is rented. Discipline is owned.",
    "Preparation is the cheat code.",
    "The tape grades your homework daily.",
    "Alerts on. Ego off. Stops set.",
    "Trade the plan. Grade the tape.",
    "Slow reads make fast exits possible.",
    "No setup, no click.",
    "Small size, clean exits, long career.",
    "The best trades feel boring.",
    "Read it, plan it, then leave it.",
    "One hour of focus beats a day of watching.",
    "Consistency first, screenshot second.",
    "Boredom is an edge in disguise.",
    "Exits before entries. Always.",
    "Keep the process, drop the feelings.",
    "Preparation is where the money hides.",
    "Plan the trade. Do not narrate it.",
    "The market pays the prepared click.",
    "Level or nothing.",
    "Fast, boring, repeatable.",
    "Stop set, mind clear, hands ready.",
    "Trade small until the tape agrees.",
    "Ape reads the filing before the bell.",
    "The routine is the strategy.",
    "Sourced homework, swift exits.",
    "No chips on the table, no tears later.",
    "Leave before the thesis gets loud.",
    "Size by plan, not by pulse.",
    "The quiet prep pays the loud open.",
    "Rules written, stops set, ego benched.",
    "Grades come from the recap, not the win.",
    "Slow study, quick exits, clean slate.",
    "Trade the record, not the story.",
]
