"""Batch 2 wrapper. Regenerates drafts_bulk2.json + preview through the canonical
engine (pools.py + humanize_rules.py + guardrails). Deduped vs batch 1, batch 3,
and hand-written drafts. Drafts only; nothing scheduled or posted.

Usage:
    python3 generate_bulk_drafts2.py            # regenerate batch 2
    python3 generate_bulk_drafts2.py --verify   # re-run checks only
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from generate_bulk_drafts import build  # noqa: E402

OUT_JSON = os.path.join(HERE, "drafts_bulk2.json")
OUT_MD = os.path.join(HERE, "drafts_bulk2_preview.md")

PREV_FILES = ("drafts_x_linkedin.json", "drafts_bulk.json", "drafts_bulk3.json")

NOTE = ("300 BULK DRAFTS, BATCH 2 (humanized: zero dashes of any kind, spellchecked). "
        "Drafts only, nothing scheduled or posted. "
        "X posts as @blitztheape. Bluesky posts as axelblitzbeaumont.bsky.social. "
        "LinkedIn posts as the company page (LINKEDIN_ORG_URN). "
        "Voice rules: BRAND VOICE doc. Generated by generate_bulk_drafts2.py via the "
        "canonical engine; deduped against all prior batches (zero overlap, verified).")

if __name__ == "__main__":
    verify_only = "--verify" in sys.argv
    ok = build(PREV_FILES, OUT_JSON, OUT_MD, 20260918, "canonical-20260918-batch2",
               NOTE, verify_only=verify_only)
    if verify_only:
        raise SystemExit(0 if ok else 1)
