"""Master line pools for Ape AI social drafts (X, Bluesky, LinkedIn).

Every line is DASH FREE (no em dashes, no hyphens; BRAND-VOICE.md humanized
rules), evergreen, fact-safe, no narrator, no invented figures.
The generator runs humanize_rules.validate_human on every composed post;
pool lines are pre-checked in main() so bad lines fail loudly with their text.
"""

DISCLAIMER = "Educational purposes only. Not financial advice."

LIMITS = {"x": 280, "bluesky": 300, "linkedin": 3000}
TARGETS = {"x": 100, "bluesky": 100, "linkedin": 100}

OPENERS = [
    "Retail investing has a research problem. It isn't the data. It's the decoding.",
    "The hardest part of investing was never access. It's translation.",
    "Most market losses start with a headline nobody finished reading.",
    "The gap between owning stocks and understanding them keeps widening.",
    "Wall Street calls it a research process. Retail gets a notification.",
    "Everything worth knowing about a public company is technically public.",
    "A stock ticker is a price. An earnings release is a story. Only one of them explains itself.",
    "The average investor has a brokerage app, a watchlist, and zero research hours.",
    "Financial media optimizes for attention. Research should optimize for accuracy.",
    "The market doesn't hide information anymore. It hides readability.",
    "The 10K exists. The earnings call exists. The footnote that matters exists.",
    "Retail investors aren't underinformed. They're overfed and unfiltered.",
    "Every investor has two jobs: deciding, and doing the homework for the deciding.",
    "Most portfolios are built from headlines. Headlines are built for clicks.",
    "The distance between a question about a stock and a plain English answer used to be a finance degree.",
    "Confidence without research isn't conviction. It's decoration.",
    "The market rewards processed information, not collected information.",
    "Nobody sets out to invest on vibes. Vibes are just what's left when research feels impossible.",
    "The most common retail research stack: a search bar and hope.",
    "Access to markets got easy. Access to understanding didn't follow.",
    "The number on the screen is the least interesting number in the filing.",
    "A watchlist is a list of questions you haven't asked yet.",
    "Every earnings season is a vocabulary test nobody signed up for.",
    "Research debt works like credit card debt: small skips, compound interest.",
    "The industry built terminals for professionals and notifications for everyone else.",
    "Reading a filing used to be the moat. Now it can be the baseline.",
    "The market speaks in filings. Most investors are told to guess.",
    "The difference between a hot take and an analysis is about 40 pages of homework.",
    "The best investors aren't the ones who know the most. They're the ones who verify the fastest.",
    "An unread portfolio update is just a rumor about your own money.",
    "An earnings call transcript is a document with feelings. Read it like one.",
    "The cheapest edge in investing is reading the thing everyone else only skimmed.",
    "Fintech spent a decade making trading fast. Reading stayed slow. That's backwards.",
    "A headline is a verdict. A filing is a trial. They rarely agree.",
    "Nobody reads the footnotes until the footnotes are all that's left to read.",
    "Portfolios don't drift on their own. Decisions made on bad information do the drifting.",
    "The market is a group project where everyone copies the loudest person's homework.",
    "A brokerage app can execute a trade in a second. Executing an idea takes weeks of homework. Only one of these is advertised.",
    "Half of investing skill is knowing what to ignore.",
    "Most 'market analysis' is someone describing a chart in past tense.",
    "The difference between data and information is the whole industry. Retail keeps being sold the first one.",
    "Questions are cheap. Unanswered questions in a portfolio are expensive.",
    "The filing was written by professionals, for professionals. Pretending otherwise is how mistakes happen.",
    "Every holding is a hypothesis. Most people have never written theirs down.",
    "Being early and being wrong look identical until the facts arrive.",
    "The most expensive part of investing is the part nobody invoices: not knowing what you don't know.",
    "Every investor gets the same 24 hours. The difference is what gets read in them.",
    "An opinion about a stock without a source is just a mood with punctuation.",
    "The market publishes everything and explains nothing. That job falls to the reader.",
    "Retail investors don't lack intelligence. They lack the interns, the terminals, and the time.",
    "Most investing mistakes are downstream of a sentence somebody didn't read.",
    "A quarterly report is a transcript of what management wants remembered. Read it that way.",
    "The scariest phrase in finance isn't on a chart. It's 'I didn't check.'",
    "You can't out trade a process you don't have.",
    "An AI can't want anything. That's exactly what makes it useful for research.",
    "Half the market's complexity is vocabulary. The other half is habit.",
    "The earnings call Q&A is the only section where management answers unscripted. It's also the least read.",
    "Nothing in a 10K changes just because a chart went up.",
    "Portfolio reviews fail when they require opening nine apps to reconstruct one week.",
    "The market sells certainty in bulk. It only delivers it by accident.",
    "Every investor is a data analyst now. Most just weren't given the tools.",
]

BODIES_SHORT = [
    "Revenue headlines don't mention the expense line. That omission is the whole game.",
    "'Beat expectations' means nothing without knowing whose expectations, and how they got set.",
    "A stock can drop and the business can be fine. It can also rip and be on fire. Price is not analysis.",
    "Every percentage has a base. Up 50% from what? During what period? Context is the story.",
    "Cash flow shows what a company can do. Net income shows what accountants want you to see.",
    "Guidance cuts get one line in the release and one day of the chart. Then people act surprised.",
    "The footnote is where the auditors put the thing they legally had to tell you.",
    "'One time charge' appears in a lot of companies every single year. Odd how recurring that is.",
    "Margin trends tell you more about a business than three quarters of revenue beats.",
    "A guidance raise funded by inventory tricks isn't growth. It's timing.",
    "The question was never 'is this a good company.' It's 'is this a good company at this price, right now.'",
    "If a thesis needs the next year to go perfectly, it isn't a thesis. It's a wish.",
    "Diversification that's really just five versions of the same trade is concentration in a costume.",
    "Position sizing is the most underrated risk tool. It's also free.",
    "The best time to write down why you bought was when you bought. The second best is now.",
    "Averaging down works. Averaging down into a broken thesis works in the other direction.",
    "Checking the price hourly is a subscription to anxiety, not a research process.",
    "Your portfolio is a record of past beliefs. Reviews are how beliefs get updated.",
    "The tax bill is part of the return. So is the spread, and the fee nobody itemized.",
    "A process you can't repeat when you're busy isn't a process. It's a mood.",
    "Black box signals get you confidence without comprehension, which is the worst combination.",
    "A red portfolio day is information about your temperament. Worth collecting.",
    "The market prices narratives first and numbers second. Research is how you invert that.",
    "The three most expensive words in investing: 'it was obvious.'",
    "Compounding gets all the press. Consistency is what actually does the compounding.",
    "There's no badge for trade count. There's a bill.",
    "Patience gets described as a personality trait. It's usually just preparation wearing a disguise.",
    "The investor who writes down their reasons can audit them later. The one who doesn't gets to invent history.",
    "Boring portfolios outperform exciting ones more often than social media suggests.",
    "Every strategy works in a backtest. Backtests don't pay for groceries.",
    "'Strong demand' isn't a number. When the release won't quantify a claim, that's the finding.",
    "Guidance is management's forecast. Forecasts are marketing with a spreadsheet attached.",
    "The earnings release and the 10Q often disagree. The 10Q wins. Almost nobody reads it.",
    "Buybacks prop EPS. Revenue does not prop itself. Different levers, different health.",
    "A competitor's press release is marketing. A competitor's capex budget is a confession.",
    "Interest expense is the quiet line that turns a good quarter into a barely okay one.",
    "Restatements don't trend on social media. They should.",
    "Cash conversion beats reported earnings. The cash account is where profitability goes to be true.",
    "'Adjusted' earnings adjust in one direction. Nobody adjusts down and calls it progress.",
    "Working capital surprises explain more missed quarters than demand does.",
    "Insider buying is a data point. Insider selling is also a data point. Neither survives contact with a real portfolio decision on its own.",
    "Sector rotation is a story people tell after the move. Useful for history, not for next week.",
    "The market can stay irrational longer than you can stay solvent. It also doesn't know you exist. Humbling on both ends.",
    "A thesis with no falsification condition isn't research. It's a tattoo.",
    "Survivorship bias is why every list of great investors is long and every list of wiped out ones is short.",
    "Liquidity is invisible until it isn't. Ask anyone who sold into a gap down.",
    "Concentration builds wealth and destroys it, using the same mechanism. Position size decides which.",
    "Averaging down into falling knives is a strategy with a museum of exhibits.",
    "'Long term hold' lasts exactly until the first red month. The label is aspirational.",
    "Rebalancing feels wrong in both directions. That's how you know it's working.",
    "Expected value requires both numbers: the payoff and the probability. Most takes supply one.",
    "Volatility is not risk. Permanent loss is risk. Confusing the two sells a lot of products.",
    "A 5% position is a decision. A 0.1% position is a rounding error pretending to be one.",
    "The smartest argument you've read about a stock was written by someone with opposite exposure.",
    "Cost basis feels like physics. The market has never once asked what you paid.",
    "Earnings estimates move before prices do. Watch revisions, not reactions.",
    "Free cash flow doesn't care about your narrative. That's why it's the line worth checking.",
    "A company that can't explain its own KPIs in one sentence is asking you to take its word for everything.",
    "Nobody ever got graded 'thorough' by the market. The market only grades results.",
    "Sell side price targets are expectations management with a decimal point.",
    "The Q&A section of an earnings call tells you what analysts worry about. That's a free map of the bear case.",
    "Management changes the words before they change the numbers. 'Solid' becomes 'resilient' becomes 'challenging.' The vocabulary moves first.",
    "A beat driven by a lower tax rate isn't a beat. It's a rounding artifact with a press release.",
    "Catalysts get all the attention. Balance sheets pay for the mistakes.",
    "'We remain confident' appears most often in the releases that age worst.",
    "The difference between a pullback and a breakdown is usually one footnote.",
    "If the explanation for a move only works in hindsight, it's a story, not a reason.",
    "Your edge isn't finding information nobody has. It's reading what everyone has, carefully.",
    "Checklists don't make you smarter. They make you consistent. Consistency compounds.",
    "The portfolio you'd build from scratch today says more than the one you're holding. Compare them.",
    "A loss you planned for is tuition. A loss you didn't plan for is a leak.",
    "Every app makes buying one tap. None makes reviewing one tap. Notice the incentive.",
    "Time spent reading beats time spent watching. One compounds, the other just feels productive.",
    "Analyst upgrades cluster near highs. That's not insight, that's momentum with a suit on.",
    "The best research habit is cheap: write down what would prove you wrong. Then go look.",
    "Seasonality gets cited like physics. It's closer to trivia.",
    "A red month tests the thesis. A green month tests the discipline. Both matter.",
    "Historical parallels are astrology for people who own spreadsheets.",
    "If you can't explain a position to a smart teenager, you don't understand it yet.",
    "Buying what you understand beats understanding what you bought. Wrong order costs money.",
    "Portfolio concentration is a decision. Portfolio drift is a default. Defaults lose.",
    "Noise has a cadence: hourly. News has a cadence: quarterly. Confusing them is expensive.",
    "The number nobody quotes is the one that decides: cash from operations minus capital spending. Ask about it.",
    "Market narrative changes weekly. Unit economics change annually. Bet on the slower clock.",
    "Every 'unprecedented' quarter has a precedent somewhere in an older filing. Research finds it.",
    "A dividend is a decision. A buyback is a decision. Growth spending is a decision. Read them like votes.",
    "Skepticism is a filter, not a personality. Apply it to bullish and bearish takes equally.",
    "The market rewards patience and punishes boredom. The problem: they feel identical at 11am.",
    "No tool can care about your money. The tool's job is making sure you can.",
    "Sell the narrative, buy the spreadsheet. One of them has footnotes.",
]

BODIES_LONG = [
    "The industry treats research access as solved. It isn't. What's solved is data access; what's missing is a translation layer between the filing and the person trying to make a decision with it. That layer is the actual product gap in retail finance.",
    "Most retail research workflows break at the same point: the moment reading turns into judgment. Collecting sources is doable. Turning 40 pages of accounting into a decision is the part nobody was taught, and it's exactly where an AI research companion earns its place.",
    "The recurring failure mode in retail investing isn't a lack of confidence. It's unstructured confidence. A decision framework doesn't need to be sophisticated. It needs to exist: what changed, what it means for the thesis, what would change your mind. Write it down; repeat it.",
    "Companies disclose an enormous amount. The disclosures are simply engineered for legal precision rather than reader speed. An AI research layer doesn't change what's disclosed; it changes who can afford to read it, which changes who gets to participate on equal footing.",
    "Earnings season demonstrates the translation gap perfectly. The release says one thing, the call elaborates, the footnote qualifies, and the headline summarizes none of it correctly. Retail investors don't need faster summaries. They need summaries that don't drop the qualifiers.",
    "The professional retail divide isn't primarily about intelligence or effort. It's about infrastructure. Professionals have aggregation, tagging, and context built into their tools. Retail has tabs. Closing that infrastructure gap is the most valuable thing fintech can build right now.",
    "There's a persistent myth that retail investors want shortcuts. In practice, most want the opposite: they want to feel that their decision survived contact with the actual numbers. The product that wins is the one that respects that instinct instead of monetizing around it.",
    "The healthiest trend in fintech is boring. Structured research, plain English explanations, and portfolio visibility aren't exciting features; they're infrastructure for better decisions. Ape AI (AskApe.com) is built on exactly that premise: research before conviction, context before action.",
    "Portfolio honesty is an underrated discipline. Not 'how did the market do' but 'what did I believe, what changed, and what am I doing about it.' Tools that surface holdings, concentration, and drift make that discipline practical instead of aspirational.",
    "The market generates more data every day than any human can read. That isn't a reason to stop reading; it's a reason to delegate the reading and keep the judgment. That division of labor is the entire thesis behind AI assisted research.",
    "Retail investing's biggest structural change in a decade isn't zero commissions. It's the arrival of research tools that explain rather than signal. Signals create dependence. Explanations build capability, and capable investors are the market's best customers.",
    "Every investment decision has two components: the information and the interpretation. The industry sells interpretations aggressively and information reluctantly. The correct order of operations is the reverse: verify the facts first, then let the interpretation compete for approval.",
    "Most retail research time is spent assembling context that already exists: what the company does, what the segment names mean, which numbers the market tracks. That assembly work is compressible. The judgment, whether the update changes the thesis, is not, and that's the part worth protecting.",
    "The filing ecosystem has a structural asymmetry: the writer spends months on it, the reader gives it minutes. AI research tools are the first mechanism that meaningfully rebalances that asymmetry, which is why resistance to them tends to come from process nostalgia rather than accuracy concerns.",
    "A portfolio review is only as honest as its inputs. Holdings spread across apps, cost basis in one place, notes in another. The friction quietly guarantees the review happens less. Consolidation isn't a feature upgrade; it's what makes the discipline possible at all.",
    "The vocabulary gap is underrated. 'Impairment,' 'revision to provision,' 'change in fair value': each is a sentence in plain English, and each carries a different implication for a thesis. Tools that translate terminology aren't simplifying investing; they're removing a gate that never actually held anything up.",
    "There's a version of AI in finance that generates confident output with no sources, and a version that shows its work. The first is a liability wearing a product badge. The second is what research assistance actually means: the claim, the source, and the qualifier, all visible.",
    "Brokerage connectivity gets discussed as convenience. It's more accurate to call it context. Without holdings data, research is generic; with it, the question stops being 'what happened in the market' and becomes 'what happened to what you actually own.' That shift changes the quality of every decision downstream.",
    "Earnings season is a stress test of information hygiene. The investors who do well aren't the ones who react fastest; they're the ones who can tell, within an hour, whether the update actually touched their thesis. That triage skill is teachable, and it's mostly tooling.",
    "The industry's favorite message is that markets are efficient and retail should simply get out of the way. The practice is different: professionals monetize the same inefficiencies, using better tools. Access to those tools is the real frontier, and it's moving faster than the messaging suggests.",
    "Skepticism of AI in investing is healthy. The useful version asks: does it cite sources, does it distinguish fact from estimate, does it say 'the filing doesn't say' when the data is missing. Products that clear that bar reduce risk. Products that don't are just faster hype.",
    "Position concentration rarely feels like a decision. It accumulates through inertia: winners left to run, adds made in familiar names, nothing deliberately rebalanced. Surfacing drift isn't hand holding; it's the difference between a strategy and a habit with equity exposure.",
    "The most durable fintech products do one boring thing reliably: they shorten the distance between a question and a sourced answer. Everything flashier (scores, signals, predictions) ages badly, because it inherits the market's uncertainty while pretending not to.",
    "Financial literacy campaigns have failed for 30 years for a predictable reason: they teach vocabulary in the abstract, at the moment of no decision. Literacy arrives when it's attached to a real holding and a real question. Tools that answer in context do more education than any curriculum.",
    "The institutional advantage was never secrecy. Public filings are public. The advantage is throughput: analysts, models, and hours that let professionals reread the same documents from different angles. AI research tools close the throughput gap for the first time, which is why this shift feels different from past fintech waves.",
    "A quiet failure mode in retail investing: research becomes consumption. Reading takes, hot takes, forecasts; all of it feels like work while replacing none of it. The fix is output. One written sentence per position: what would make you sell. If you can't fill it in, the research isn't done.",
    "Trust in AI financial tools will be earned through failure behavior, not accuracy claims. The question isn't whether the answer is right; it's what the tool does when it doesn't know. Tools that say 'the filing doesn't say' are worth more than tools that always have an answer. Uncertainty disclosure is the product.",
    "Every portfolio has a shadow portfolio: the trades considered and skipped. Reviewing it is uncomfortable and useful; skipped ideas reveal whether the process filters well or just filters familiar. A research companion that logs questions asked makes that visible, and visibility is where improvement starts.",
    "The vocabulary of earnings releases is a status system. Terms like 'nonrecurring' and 'adjusting for' do rhetorical work; they frame a number before it's read. Teaching plain English equivalents isn't dumbing anything down; it's ending a dialect whose main function was gatekeeping.",
    "Brokerage connections are a trust decision, and the industry keeps framing them as convenience. The honest pitch: read only access, clear revocation, and a visible list of what the tool can and cannot see. That standard is higher than most apps meet, and it's the only one that deserves the data.",
    "Most financial content is optimized for the moment after reading: the reaction. Research is optimized for the moment after that: the decision. The two genres look identical in a feed and behave nothing alike over a year. Distinguishing them is the first skill worth building, for investors and for tools alike.",
    "There's an argument that retail investors shouldn't pick stocks at all, just index and move on. Fair, for many. But millions will pick stocks anyway, and they deserve better inputs than a notification and a vibe. Meeting people where they actually are beats correcting them from where they should be.",
    "Earnings call questions are the closest thing markets have to cross examination. Analyst questions reveal the consensus bear case; evasive answers reveal where management feels thin. An AI layer that summarizes those exchanges by theme does more for research quality than any new chart.",
    "The best product decision in fintech is subtractive: remove the steps between a question and its sourced answer. Every added metric, score, or badge is another thing that has to earn trust. The core loop, ask, get context, decide, is enough. It always was; the industry just monetizes complication better.",
]

CLOSERS_SHORT = [
    "Ask better questions. That's the whole edge.",
    "Research first. Conviction after.",
    "The tool is Ape AI. The judgment stays yours.",
    "Verify, then decide.",
    "Ape AI exists for exactly this gap.",
    "Plain English in, plain English out.",
    "AskApe.com. Research at reading speed.",
    "Less guessing. More reading. That's the pitch.",
    "The homework is done. The decision is yours.",
    "Bring the questions. Ape AI brings the context.",
    "Read the release. Then decide.",
    "Context beats conviction. Every time.",
    "The filing is free. The regret isn't.",
    "Ape AI reads it. You decide.",
    "Sourced answers beat confident guesses.",
    "Do the boring layer. Keep the judgment.",
    "Ask Ape AI. Keep your evenings.",
    "Numbers first. Narrative second.",
    "The footnote called. It matters.",
    "Less vibes. More filings.",
    "AskApe.com. Questions welcome.",
    "Research is the moat now.",
    "Verify once. Panic less.",
    "The work is reading. The tool helps.",
    "Plain answers, sources attached.",
    "Read the Q&A. It's the honest part.",
    "Write the thesis down. Then you'll know.",
    "Sourced or silent. That's the bar.",
    "One filing read beats ten takes watched.",
    "Ape AI. The reading, handled.",
    "Ask the boring question. It pays best.",
    "The footnote never sleeps.",
    "Slower reads, faster decisions.",
    "Check the cash. Then talk.",
    "Your process is your edge.",
    "AskApe.com. Bring the skepticism.",
    "Fewer tabs. More answers.",
    "The judgment stays yours. The homework doesn't.",
    "Research like you mean it.",
    "Numbers don't negotiate. Read them.",
]

CLOSERS_CTA = [
    "What does your research process actually look like? Genuine question: the comment section is the best part of these posts.",
    "Where does your research time actually go? Most people have never measured it. Worth doing once.",
    "If you could ask one plain English question about any company and get a sourced answer, what would it be?",
    "Curious how others separate signal from noise. What's the one filter that's saved you the most money?",
    "What's the first thing you check after the headline? Comment section is a free education. Add yours.",
    "If this is the kind of research you want more of, that's the product: AskApe.com.",
    "What's a term you've had to look up in the middle of a filing? Someone else needs the answer too. Drop it below.",
    "Genuine question: how many hours a week do you spend on research, and how many do you wish you did?",
    "If you use an AI tool for research, what would it need to do before you trusted it?",
    "What's the most useless market headline you've seen this week? Wrong answers welcome, citations preferred.",
    "What would make connecting a brokerage to a tracking tool actually worth it? Curious where the trust line is.",
    "If this was useful, the product is AskApe.com, built for exactly these questions.",
    "What's the one filing or report you keep meaning to read and never do? Honest answers welcome.",
    "If your research process had a weekly ritual, what would it be? Building a list of the good ones.",
    "What convinced you to trust (or distrust) an AI research tool? The answers shape what gets built.",
    "Drop the best piece of financial jargon you've survived. Translation attempts encouraged.",
    "What question did you ask about a stock this month that took too long to answer?",
]

MID_CONNECTORS = [
    "Here's the uncomfortable part:",
    "The data agrees:",
    "Consider the mechanic:",
    "Why it matters:",
    "What most people miss:",
    "The industry rarely says this out loud:",
    "The uncomfortable math:",
    "Ask anyone who's done the reading:",
    "The pattern holds across sectors:",
    "What the filings say:",
    "The uncomfortable version:",
    "Ask anyone who has cleaned up a mess:",
    "Here's the mechanism:",
    "What the Q&A reveals:",
]
